name: Tan
favicon: null
layout_spectrum: 0.41806
typography_spectrum: 0.747430611634627
title: Tan Nuyen Graphic Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21618675044737756
  lightness: 0.048650286393240094
  saturation: 0.12918950873427093
  rhythmicContrast: 0.14516547950915992
purpose: []
